### ISSUE TITLE
Add Support for listing all available shares

### ISSUE THREAD

**Issue by YoSev** [stacktitan/smb#3]
Hello,

even tho i read this project is just a very basic implementation, do you plan to maintain this library?

I would like to add support for listing all available shares (public/hidden) but i can't manage to do so..
Any Ideas?

**Comment by homco-rmd** [comment]
@john-dev I have interest to do the same; I might try and take a stab at it.

**Comment by SilentGopherLnx** [comment]
hi. I use linux and I can do with smb everything by going in /run/user/1000/gvfs
The only thing I need is listing all available shares when i connect without password.
So, I need this too (on pure golang) =)
